#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh 

bspc monitor -d       

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-terminal desktop='^1' focus=on follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Thunar desktop=^3 focus=on follow=on
bspc rule -a Pcmanfm desktop=^3 focus=on follow=on
bspc rule -a Ranger desktop=^3 focus=on follow=on
bspc rule -a Subl desktop=^4 focus=on follow=on
bspc rule -a telegram-desktop desktop=^5 focus=on follow=on

