require('plugin')
require('options')
require('keymappings')
require('colorscheme')

-- Plugins config
require('plugins/autopairs')
require('plugins/autosave')
require('plugins/bufferline')
require('plugins/cmp')
require('plugins/comments')
require('plugins/impatient')
require('plugins/indentline')
require('plugins/lualine')
require('plugins/nvim-tree')
require('plugins/project')
require('plugins/telescope')
require('plugins/toggleterm')
require('plugins/treesitter')
