require("plugins")
require("options")
require("keymappings")

-- Plugins
require("lsp")
require("plugins/cmp")
require("plugins/barbar")
require("plugins/gitsigns")
require("plugins/autosave")
require("plugins/nvim-tree")
--require("plugins/nvim-dap")
--require("plugins/nvim-dap-ui")
require("plugins/telescope")
require("plugins/autopairs")
require("plugins/colorscheme")
require("plugins/indent-line")
require("plugins/nvim-comments")
